Cis bench wif
alice-biometrics/actions pull request #70
Opened 2022-10-26 14:35 UTC by sgarcia1996

2022-10-26 15:18 UTC, franciscorode requested changes

2022-10-26 15:18 UTC, franciscorode commented on .github/workflows/k8s-security-cis-bench.yml
> +          ctoken_format: 'access_token'
there is a typo here

2022-10-26 15:30 UTC, sgarcia1996 commented on .github/workflows/k8s-security-cis-bench.yml
> +          ctoken_format: 'access_token'
I correct the error

2022-10-27 06:43 UTC, franciscorode approved these changes

2022-10-31 09:18 UTC, merged